/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : RX26TFADFM_UART_DMA_Motor.c
*  Description  : Main Program
*  Creation Date: 2026-02-14
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include "app/uart_dma/uart_dma_demo.h"

void main(void);

void main(void)
{
    uart_dma_demo_run_forever();
}
